### ISSUE TITLE
The `Checkbox` component must be used as a child of `CheckboxGroup`.

### ISSUE THREAD

**Issue by billyperalta89** [ziad-saab/react-checkbox-group#56] opened 2018-09-12 17:24 UTC
```
<CheckboxGroup name="Winning">
                  {Object.keys(this.state.WinningChoices).map(key => (
                    <label>
                      <Checkbox value={this.state.WinningChoices[key]} />
                      {this.state.WinningChoices[key]}
                    </label>
                  ))}
                </CheckboxGroup>
```

whats wrong with this?

**Comment by tasiek** [comment] 2018-09-20 11:59
Duplicate of https://github.com/ziad-saab/react-checkbox-group/issues/34

You just need to use `checkboxDepth={2}`.

**Comment by andrew-knott** [comment] 2018-10-15 22:39
I'm still having an issue with checkboxDepth not working.

The `Checkbox` component must be used as a child of `CheckboxGroup`

`                    <CheckboxGroup
                      name={"field68408292"}
                      checkboxDepth={4}
                      value={["Gallery Newsletters"]} 
                      onChange={this.enquiryChanged}>


                      <Col md={6} className="pad-horizontal-xs-none postpad-horizontal-md-xtiny">
                        <label>
                          <Checkbox value="Option 1" />
                          <span className="form-small-print prepad-horizontal-xs-xtiny">Option 1</span>
                        </label>
                      </Col>
                      <Col md={6} className="pad-horizontal-xs-none prepad-horizontal-md-xtiny">
                        <label>
                          <Checkbox  value="Option 2" />
                          <span className="form-small-print prepad-horizontal-xs-xtiny">Option 2</span>
                        </label>
                      </Col>
                      <Col md={6} className="pad-horizontal-xs-none postpad-horizontal-md-xtiny">
                        <label>
                          <Checkbox  value="Option 3" />
                          <span className="form-small-print prepad-horizontal-xs-xtiny">Option 3</span>
                        </label>
                      </Col>
                      <Col md={6} className="pad-horizontal-xs-none prepad-horizontal-md-xtiny">
                        <label>
                          <Checkbox   value="Option 4" />
                          <span className="form-small-print prepad-horizontal-xs-xtiny">Option 4</span>
                        </label>
                      </Col>
                    </CheckboxGroup>`

**Comment by andrew-knott** [comment] 2018-10-16 00:02
It looks like it's always returning 'true' at this check...

 if (!child.$$typeof) {
          return child;

like $$typeof is missing

**Closed** 2019-07-18 22:15 UTC
